DM-41029: Update Pydantic model for Schema class
lsst/felis pull request #36
Opened 2024-01-19 23:24 UTC by andy-slac

The `version` attribute can accept either string or `SchemaVersion` instance.

2024-01-19 23:26 UTC, andy-slac commented
@JeremyMcCormick, could you check my one-line update? I want to be able to specify `version` attribute as a single string in YAML (in addition to `SchemaVersion` dict), that should keep things simple for many potential uses.

2024-01-22 22:20 UTC, JeremyMcCormick commented
The current syntax would be:

```
version:
  current: "1.2.3"
```

This change just seems to remove the need for the separate key. Is it needed?

Version functionality is not used in the SDM schemas at the moment. I will discuss with @gpdf if we should allow a string here rather than requiring the keys.

2024-01-22 22:49 UTC, andy-slac commented
The documentation (that I wrote) explicitly says that string-only version is allowed too. I think this is useful simplification. None of the schema is using versions yet, but I was trying to add version support to `apdb.yaml` (https://github.com/lsst/sdm_schemas/pull/171) and discovered that your new validation code disallows it.

2024-01-23 01:24 UTC, JeremyMcCormick commented
> The documentation (that I wrote) explicitly says that string-only version is allowed too. I think this is useful simplification. None of the schema is using versions yet, but I was trying to add version support to `apdb.yaml` ([lsst/sdm_schemas#171](https://github.com/lsst/sdm_schemas/pull/171)) and discovered that your new validation code disallows it.

Okay, it seems reasonable to add this support. I will leave more comments in a review.

2024-01-23 01:28 UTC, JeremyMcCormick requested changes
@andy-slac Can you add a test case for this functionality in `tests/test_datamodel.py` ?

You can duplicate line 318 and set a version string here:

```
Schema(name="testSchema", id="#test_sch_id", tables=[test_tbl])
```

Otherwise, this looks reasonable since it was part of the documentation and possible using the original data model.

2024-01-24 23:51 UTC, JeremyMcCormick approved these changes
Thank you for adding the test case. This looks good now.

2024-01-24 23:52 UTC, merged